export const companiesWorked = [
  {
    id: 1,
    name: "Peacedev",
    startDate: "October",
    endDate: "Current",
    role: "Front End Developer",
    thingsWorkedOn: ["WIP"],
  },
  {
    id: 2,
    name: "Lovepop",
    startDate: "January",
    endDate: "July 2022",
    link: "https://www.lovepop.com/",
    role: "Software Engineer",
    thingsWorkedOn: [
      "Developed features meant to increase revenue per session such as Send a Surprise, Upsells",
      "Strengthened site usability and accessibility",
      "Implemented A/B Feature Testing",
      "Shipped high quality code with a focus on scalability, performance and accessibility",
      "Converted our codebase from Javascript to Typescript",
    ],
  },
  {
    id: 3,
    name: "Indra",
    startDate: "September",
    endDate: "January 2022",
    link: "https://www.indracompany.com/en/",
    role: " Software Developer",
    thingsWorkedOn: [
      "Migrating web modules from AngularJS to ExtJS",
      "Creation of Restful APIs with Spring Boot",
      "Developed various React Forms for both web and mobile",
    ],
  },
  {
    id: 4,
    name: "Proteccion",
    startDate: "February",
    endDate: "August 2021",
    link: "https://www.proteccion.com/contenidos/",
    role: "Junior Software Developer",
    thingsWorkedOn: [
      "Launched several responsive features using React, React-Dashboard and Redux",
      "Managed endpoints in the back-end using Django to retrieve data for the front-end",
    ],
  },
  {
    id: 5,
    name: "Proteccion",
    startDate: "February",
    endDate: "August 2021",
    link: "https://www.proteccion.com/contenidos/",
    role: "Junior Software Developer",
    thingsWorkedOn: [
      "Launched several responsive features using React, React-Dashboard and Redux",
      "Managed endpoints in the back-end using Django to retrieve data for the front-end",
    ],
  },
];
