//work experience
export const companiesWorked = [
  // {
  //   id: 1,
  //   name: 'WebRun Labs',
  //   startDate: 'February 2023',
  //   endDate: 'June 2023',
  //   role: 'Front End Developer',
  //   thingsWorkedOn: [
  //     'Developed, using React, a diverse range of landing pages catering to different industries, showcasing adaptability and veratility in design and implementation',
  //     'Took a leadership role in mentoring and guiding a junior developer, helping them in their professional development',
  //     'Collaborated closely with the design team to ensure pixel-perfect execution of web applications',
  //     'Utilized Airtable to efficienly manage client data and streamline processes, resulting in the successful implementation of marketing and email campaigns to drive client engagement and increase conversion rates rates',
  //   ],
  // },
  {
    id: 2,
    name: 'Peacedev',
    startDate: 'August 2022',
    endDate: 'June 2023',
    role: 'Front End Developer',
    thingsWorkedOn: [
      'Redesigned the company corporate website',
      'Implemented E2E testing using Cypress',
      'Developed, using React, a diverse range of landing pages catering to different industries, showcasing adaptability and veratility in design and implementation',
      'Took a leadership role in mentoring and guiding a small team of three junior developers, fostering their skills professional growth',
      'Served as primary technical lead on multiple major projects, collaborating across teams and levels when making code architecture decisions',
      'Communicated with stakeholders about roadmap progress and championed solutions that met requirements with quick turnaround',
      'Served as the primary connection between design and development',
      'Utilized Airtable to efficienly manage client data and streamline processes, resulting in the successful implementation of marketing and email campaigns to drive client engagement and increase conversion rates rates',
    ],
  },
  {
    id: 3,
    name: 'Lovepop',
    startDate: 'January 2022',
    endDate: 'July 2022',
    link: 'https://www.lovepop.com/',
    role: 'Software Engineer',
    thingsWorkedOn: [
      'Developed features meant to increase revenue per session such as Send a Surprise, Upsells',
      'Strengthened site usability and accessibility',
      'Implemented A/B Feature Testing',
      'Shipped high quality code with a focus on scalability, performance and accessibility',
      'Converted our codebase from Javascript to Typescript',
    ],
  },
  {
    id: 4,
    name: 'Indra',
    startDate: 'February 2021',
    endDate: 'January 2022',
    link: 'https://www.indracompany.com/en/',
    role: ' Software Developer',
    thingsWorkedOn: [
      'Migrating web modules from AngularJS to ExtJS',
      'Creation of Restful APIs with Spring Boot',
      'Developed various React Forms for both web and mobile',
      'Launched several responsive features using React, React-Dashboard and Redux',
      'Managed endpoints in the back-end using Django to retrieve data for the front-end',
    ],
  },
]
